#!/usr/bin/env python3
"""Generate docs/BEHAVIOR.md: what the host suite says the firmware does.

Nothing here is authored twice. Three things already in the tree are collected:

  the case name        `TEST_CASE("button: a stable press emits exactly one event")`
  the subject          the `button` half of that name, which groups the cases
  the prose            the comment heading a test file, or heading one case

doctest's junit reporter is the only output carrying both a name and its file, so
the suite is run (0.3 s) rather than listed, and only cases that actually
registered are documented. The prose is read back out of the sources.

Every name must read `subject: what holds`. A name that does not is refused here,
because a case that cannot state its subject cannot document anything either.
"""
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIRMWARE = os.path.join(ROOT, "firmware")
TEST_BINARY = os.path.join(FIRMWARE, "build", "skyblip_tests")
OUTPUT = os.path.join(ROOT, "docs", "BEHAVIOR.md")
SUBJECT_SEPARATOR = ": "

LAYERS = {
    "core": "core - the logic the radio and the screen are built on",
    "ui": "ui - screens, widgets and input",
    "hardware": "hardware - one folder per part, driver against model",
    "products": "products - a SKU end to end, and the committed scenarios",
}

HEADER = """# Behavior

{cases} host test cases over {subjects} subjects in {files} files, as the doctest suite states them. A test name is a claim, and the file above it is where the claim is checked. Quoted prose is the comment the test file or the case carries.

Generated by `scripts/behavior_index.py` from the run itself, and diffed in CI. Do not edit: rename the test case, or write the comment it is missing.
"""

FOOTER = """
---

{documented} of {files} test files open with a comment saying what they pin down. The rest state it in their case names alone.
"""


def main():
    cases = run_suite()
    misnamed = [name for _, name in cases if SUBJECT_SEPARATOR not in name]
    if misnamed:
        report(f"test case names must read `subject{SUBJECT_SEPARATOR}what holds`:")
        for name in misnamed:
            report(f"  {name}")
        return 1

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as out:
        out.write(render(cases))
    report(f"{len(cases)} cases -> {os.path.relpath(OUTPUT, ROOT)}")
    return 0


def run_suite():
    if not os.path.exists(TEST_BINARY):
        report(f"no test binary at {os.path.relpath(TEST_BINARY, ROOT)}: run `make test` first")
        sys.exit(1)
    # cwd is firmware/ because the scenario cases open scenarios/*.json by relative path.
    run = subprocess.run(
        [TEST_BINARY, "--reporters=junit"], cwd=FIRMWARE, capture_output=True, text=True
    )
    if run.returncode != 0:
        report("the suite is failing, so its names are not documentation yet")
        sys.exit(1)
    root = ET.fromstring(run.stdout)
    return [(case.get("classname"), case.get("name")) for case in root.iter("testcase")]


def render(cases):
    by_file = defaultdict(list)
    for path, name in cases:
        by_file[path].append(name)
    prose = {path: read_prose(path) for path in by_file}
    documented = sum(1 for path in by_file if prose[path][0])

    lines = [
        HEADER.format(
            cases=len(cases),
            subjects=len({subject_of(name) for _, name in cases}),
            files=len(by_file),
        )
    ]
    for layer, paths in sorted(group_by_layer(by_file).items()):
        lines.append(f"## {LAYERS.get(layer, layer)}\n")
        for path in sorted(paths):
            intro, notes = prose[path]
            lines.append(f"### {path}\n")
            if intro:
                lines.append(f"{intro}\n")
            lines.extend(render_subjects(by_file[path], notes))
    lines.append(FOOTER.format(documented=documented, files=len(by_file)))
    return "\n".join(lines).rstrip() + "\n"


def render_subjects(names, notes):
    by_subject = defaultdict(list)
    for name in names:
        by_subject[subject_of(name)].append(name)

    lines = []
    for subject, group in sorted(by_subject.items()):
        lines.append(f"**{subject}**\n")
        for name in sorted(group):
            lines.append(f"- {name.split(SUBJECT_SEPARATOR, 1)[1]}")
            if name in notes:
                lines.append(f"  > {notes[name]}")
        lines.append("")
    return lines


def subject_of(name):
    return name.split(SUBJECT_SEPARATOR, 1)[0]


COMMENT_BLOCK = r"(?:[ \t]*//[^\n]*\n)+"
FILE_INTRO = re.compile(rf"\A{COMMENT_BLOCK}")
CASE_NOTE = re.compile(rf"^({COMMENT_BLOCK})TEST_CASE\(\s*\"((?:[^\"\\]|\\.)*)\"", re.M)


def read_prose(path):
    """The file's opening comment, and the comment heading each documented case."""
    with open(os.path.join(FIRMWARE, path)) as source:
        text = source.read()
    intro = FILE_INTRO.match(text)
    notes = {
        unescape(match.group(2)): flatten(match.group(1)) for match in CASE_NOTE.finditer(text)
    }
    return flatten(intro.group()) if intro else "", notes


def unescape(literal):
    return literal.replace('\\"', '"').replace("\\\\", "\\")


def flatten(comment):
    return " ".join(line.strip().lstrip("/").strip() for line in comment.strip().splitlines())


def group_by_layer(by_file):
    layers = defaultdict(list)
    for path in by_file:
        layers[os.path.basename(os.path.dirname(path))].append(path)
    return layers


def report(message):
    print(message, file=sys.stderr)


if __name__ == "__main__":
    sys.exit(main())
